# Generated by Django 2.2.5 on 2019-09-25 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_auto_20190920_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Useful Item', max_length=50)),
                ('description', models.CharField(default='This does everything', max_length=128)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='player',
            name='items',
            field=models.ManyToManyField(to='adv.Item'),
        ),
    ]
