# Generated by Django 2.2.5 on 2019-09-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0004_auto_20190924_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='items',
            field=models.ManyToManyField(to='adv.Item'),
        ),
    ]
