# Generated by Django 2.2.5 on 2019-09-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0006_auto_20190925_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
