# Generated by Django 2.2.5 on 2019-09-25 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0009_auto_20190925_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
    ]
