# Generated by Django 2.2.5 on 2019-09-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0011_auto_20190925_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='origin',
            field=models.CharField(default='That place', max_length=12),
        ),
    ]
