# Generated by Django 2.2.5 on 2019-09-26 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0012_item_origin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='polymorphic_ctype',
        ),
    ]
