# Generated by Django 2.2.5 on 2019-09-26 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0014_auto_20190925_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='origin',
        ),
    ]
